#!/bin/bash

# This script must be executed when you are in UIFrameworks directory
# Example:
# cd YourProjectPath/UIFrameworks
# ./DeleteBinObj

rm -r EOS.UI.Droid/bin
rm -r EOS.UI.Droid/obj
rm -r EOS.UI.Droid.Sandbox/bin
rm -r EOS.UI.Droid.Sandbox/obj